version: '3.8'

services:
  # PostgreSQL 資料庫
  postgres:
    image: postgres:15-alpine
    container_name: chatbot_postgres
    environment:
      POSTGRES_DB: chatbot_db
      POSTGRES_USER: chatbot_user
      POSTGRES_PASSWORD: ${DB_PASSWORD:-chatbot_password}
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --locale=C"
    volumes:
      - /Users/caimingzhi/Documents/Avery的專案\(嚴謹版\)/思考機器人/data/postgres:/var/lib/postgresql/data
      - ./migrations/init:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    restart: unless-stopped
    command: >
      postgres
      -c shared_preload_libraries=pg_stat_statements
      -c max_connections=200
      -c shared_buffers=256MB
      -c effective_cache_size=1GB
      -c maintenance_work_mem=64MB
      -c checkpoint_completion_target=0.9
      -c wal_buffers=16MB
      -c default_statistics_target=100
      -c timezone=Asia/Taipei

  # Redis 快取
  redis:
    image: redis:7-alpine
    container_name: chatbot_redis
    command: redis-server --appendonly yes --requirepass ${REDIS_PASSWORD:-redis_password}
    volumes:
      - /Users/caimingzhi/Documents/Avery的專案\(嚴謹版\)/思考機器人/data/redis:/data
    ports:
      - "6380:6379"
    restart: unless-stopped

  # Web 應用程式
  web:
    image: chatbot-web:latest
    container_name: chatbot_web
    environment:
      - DATABASE_URL=postgresql://chatbot_user:chatbot_password@postgres:5432/chatbot_db
      - REDIS_URL=redis://:redis_password@redis:6379/0
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - LINE_CHANNEL_ACCESS_TOKEN=${LINE_CHANNEL_ACCESS_TOKEN}
      - LINE_CHANNEL_SECRET=${LINE_CHANNEL_SECRET}
      - DEBUG=${DEBUG:-false}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis
    restart: unless-stopped
    volumes:
      - ./app:/app/app
    command: >
      sh -c "
        echo 'Waiting for database...' &&
        python -c 'import time; time.sleep(5)' &&
        echo 'Starting application...' &&
        python -m uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
      "

# volumes 已改為使用絕對路徑
